writing_task:
  description: >
    Craft a compelling and engaging Medium article section about {topic} based on the provided research and content plan. Focus on creating
    viral-worthy content that combines storytelling with practical value, using proven Medium article formats. Hook readers from the first
    sentence while delivering unique insights. Ensure the section has attention-grabbing subheadings and smooth transitions.

    Section: {section}
  expected_output: >
    A well-crafted Medium article section that blends entertainment and education, keeping readers engaged with clever hooks,
    relatable stories, and unexpected insights. The content should follow Medium's best practices for viral articles while
    delivering genuine value about {topic}.

    Format the content with strategic use of headings, subheadings, and formatting elements that maintain visual interest
    and enhance readability on Medium's platform.
  agent: content_writer

editing_task:
  description: >
    Transform the draft section into a Medium masterpiece by optimizing every element for maximum engagement and shareability.
    Focus on crafting powerful paragraphs and strategic use of formatting (bold text, pull quotes, etc.) to maintain visual
    interest. Ensure the content follows Medium's best practices for viral articles.

    Section: {section}
  expected_output: >
    A polished and optimized Medium article section that maximizes read time, engagement, and shares while maintaining
    authenticity and value. The content should demonstrate keen understanding of Medium's algorithm and reader psychology.

    Return only the enhanced section content, formatted according to Medium's best practices.
  agent: editor

quality_review_task:
  description: >
    Evaluate the section's viral potential and ensure it hits all the marks for Medium success - captivating hook, valuable
    insights, emotional connection, and clear takeaways. Verify that the content maintains the perfect balance between
    entertainment and education while delivering on the promised value to readers.

    Section: {section}
  expected_output: >
    An improved version of the section that demonstrates that special mix of uniqueness, value, and emotional resonance that
    Medium readers love to share. The content should be formatted according to Medium's best practices with strategic use of
    formatting elements.

    Include relevant citations and references where appropriate to add credibility. Return only the enhanced content, not the
    review feedback.
  agent: quality_reviewer
